[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
test_zk = "bY7UG7vYiS3dttRd9DZVDzpJnpFaBWA7Qc93Td9kWbf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
